"""No-op writes must not pollute the audit trail.

config_changes.log is the fastest way to answer "when did this knob move".
Forcing a reload by POSTing a key to the value it already had (which is what
happened before /api/config/reload existed) filled it with rows like
  ibkr.quote_wait_ms | '500' → '500'
that say nothing and bury the real entries.
"""
import pytest

from app.core.config_manager import _AppConfig


@pytest.fixture
def cfgfile(tmp_path, monkeypatch):
    p = tmp_path / "config.ini"
    p.write_text("[trading]\nbuy_slippage = 0.04\nsl_pct = -20\n", encoding="utf-8")
    (tmp_path / "logs").mkdir()
    import app.core.config_manager as cm
    monkeypatch.setattr(cm, "CONFIG_PATH", p)
    return p, tmp_path / "logs" / "config_changes.log"


def _audit(path):
    return path.read_text(encoding="utf-8").strip().splitlines() if path.exists() else []


class TestNoOpAudit:
    def test_unchanged_value_is_not_audited(self, cfgfile, monkeypatch):
        p, audit = cfgfile
        import app.core.config_manager as cm
        monkeypatch.setattr(cm, "EDITABLE_KEYS", {("trading", "buy_slippage")})
        m = _AppConfig()
        errs = m.set_and_save([{"section": "trading", "key": "buy_slippage", "value": "0.04"}])
        assert errs == []
        assert _audit(audit) == [], "writing the same value must leave no audit row"

    def test_real_change_is_audited(self, cfgfile, monkeypatch):
        p, audit = cfgfile
        import app.core.config_manager as cm
        monkeypatch.setattr(cm, "EDITABLE_KEYS", {("trading", "buy_slippage")})
        m = _AppConfig()
        m.set_and_save([{"section": "trading", "key": "buy_slippage", "value": "0.07"}])
        lines = _audit(audit)
        assert len(lines) == 1
        assert "0.04" in lines[0] and "0.07" in lines[0]

    def test_noop_still_persists_and_succeeds(self, cfgfile, monkeypatch):
        """A no-op is still 'applied' — the caller asked for a state, and it holds."""
        p, audit = cfgfile
        import app.core.config_manager as cm
        monkeypatch.setattr(cm, "EDITABLE_KEYS", {("trading", "buy_slippage")})
        m = _AppConfig()
        assert m.set_and_save([{"section": "trading", "key": "buy_slippage", "value": "0.04"}]) == []
        assert "buy_slippage = 0.04" in p.read_text(encoding="utf-8")

    def test_mixed_batch_audits_only_the_real_one(self, cfgfile, monkeypatch):
        p, audit = cfgfile
        import app.core.config_manager as cm
        monkeypatch.setattr(cm, "EDITABLE_KEYS",
                            {("trading", "buy_slippage"), ("trading", "sl_pct")})
        m = _AppConfig()
        m.set_and_save([
            {"section": "trading", "key": "buy_slippage", "value": "0.04"},   # no-op
            {"section": "trading", "key": "sl_pct", "value": "-25"},          # real
        ])
        lines = _audit(audit)
        assert len(lines) == 1 and "sl_pct" in lines[0]


class TestReloadReadsDisk:
    def test_reload_picks_up_an_external_edit(self, cfgfile):
        p, _ = cfgfile
        m = _AppConfig()
        assert m.get("trading", "sl_pct") == "-20"
        p.write_text("[trading]\nbuy_slippage = 0.04\nsl_pct = -35\n", encoding="utf-8")
        m.reload()
        assert m.get("trading", "sl_pct") == "-35"


class TestDiskEditIsAudited:
    """A knob edited on disk moves money as much as one edited in the portal.

    The secondary instances get every one of their edits this way — their config
    is generated by scripts/ops/setup-instance.sh and picked up with
    /api/config/reload — so without an audit row their Change History reads as
    "nothing ever changed".
    """

    def test_disk_edit_is_recorded_with_old_and_new(self, cfgfile):
        p, audit = cfgfile
        m = _AppConfig()
        before = m.as_dict()
        p.write_text("[trading]\nbuy_slippage = 0.04\nsl_pct = -35\n", encoding="utf-8")
        m.reload()
        after = m.as_dict()

        moved = [(s, k) for s in set(before) | set(after)
                 for k in set(before.get(s, {})) | set(after.get(s, {}))
                 if before.get(s, {}).get(k) != after.get(s, {}).get(k)]
        m.append_audit([m.audit_line(s, k, before.get(s, {}).get(k),
                                     after.get(s, {}).get(k), source="disk edit")
                        for s, k in moved])

        lines = _audit(audit)
        assert len(lines) == 1, "one knob moved, one row"
        assert "trading.sl_pct" in lines[0]
        assert "'-20' → '-35'" in lines[0]
        assert "(disk edit)" in lines[0], "the trail must say where the edit came from"
        # The history endpoint splits on '|' and keeps rows with exactly 3 fields.
        assert len(lines[0].split("|")) == 3

    def test_reload_with_no_change_writes_nothing(self, cfgfile):
        p, audit = cfgfile
        m = _AppConfig()
        before = m.as_dict()
        m.reload()
        after = m.as_dict()
        moved = [(s, k) for s in set(before) | set(after)
                 for k in set(before.get(s, {})) | set(after.get(s, {}))
                 if before.get(s, {}).get(k) != after.get(s, {}).get(k)]
        m.append_audit([m.audit_line(s, k, None, None) for s, k in moved])
        assert _audit(audit) == [], "a no-op reload must stay out of the trail"

    def test_secret_rotation_never_reaches_the_trail(self, cfgfile):
        """as_dict masks SENSITIVE_KEYS, so a rotated token compares equal to
        itself and cannot be written into a log the dashboard serves."""
        p, audit = cfgfile
        p.write_text("[trading]\nsl_pct = -20\n[discord]\ntoken = old-secret\n",
                     encoding="utf-8")
        m = _AppConfig()
        before = m.as_dict()
        p.write_text("[trading]\nsl_pct = -20\n[discord]\ntoken = new-secret\n",
                     encoding="utf-8")
        m.reload()
        after = m.as_dict()
        moved = [(s, k) for s in set(before) | set(after)
                 for k in set(before.get(s, {})) | set(after.get(s, {}))
                 if before.get(s, {}).get(k) != after.get(s, {}).get(k)]
        m.append_audit([m.audit_line(s, k, before.get(s, {}).get(k),
                                     after.get(s, {}).get(k), source="disk edit")
                        for s, k in moved])
        trail = "\n".join(_audit(audit))
        assert "old-secret" not in trail and "new-secret" not in trail
